name: 'Generate Code'
description: 'Generates files using OpenAI API'
inputs:
  branch_name:
    description: 'Branch Name'
    required: false
    default: 'llm-code-gen'
  descriptions:
    description: 'Descriptions (comma-separated)'
    required: true
  openai_token:
    description: 'OpenAI API Token'
    required: true
  model_name:
    description: 'Model Name'
    required: false
    default: 'gpt-3.5-turbo-16k-0613'
  github_token:
    description: 'Token to push to the repo.'
    required: true
  max_tokens:
    description: 'Maximum tokens for OpenAI API call'
    required: false
    default: '300'
  python_version:
    description: 'Python version'
    required: false
    default: '3.x'
  python_log_level:
    description: 'Log level used in the python script'
    required: true
    default: 'INFO'
  force_push:
    description: 'Enable force push to the remote branch'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version}}

  - name: Install dependencies
    shell: bash
    run: pip install -r requirements.txt

  - name: Generate Files
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
    run: |
      FORCE_PUSH_FLAG=""
      if [ "${{ inputs.force_push }}" = "true" ]; then
        FORCE_PUSH_FLAG="--force_push"
      fi
      python generate_files.py --branch_name '${{ inputs.branch_name }}' --descriptions '${{ inputs.descriptions }}' --openai_token '${{ inputs.openai_token }}' --model_name '${{ inputs.model_name }}' --max_tokens '${{ inputs.max_tokens }}' --log_level '${{ inputs.python_log_level }}' $FORCE_PUSH_FLAG
