name: Test Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Action Test
      uses: ./
      with:
        branch_name: 'test-ci-setup'
        descriptions: 'linting and formatting for python with ruff'
        openai_token: ${{ secrets.OPENAI_API_TOKEN }}
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
