name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CI/CD Setup Action
      uses: ./
      with:
        branch_name: 'test-ci-setup'
        descriptions: 'linting for python'
        openai_token: ${{ secrets.OPENAI_API_TOKEN }}
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
