name: Test Action

on:
  workflow_call:
    secrets:
      OPENAI_API_TOKEN:
        required: true
      WORKFLOW_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Action Test
      uses: ./
      with:
        branch_name: 'test-ci-setup'
        descriptions: 'linting and formatting for python with flake8 and black'
        openai_token: ${{ secrets.OPENAI_API_TOKEN }}
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
